/**
 * Tarusho.Server
 * Tarusho server API reference
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import {ApiConfig} from '../config'
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class ReservationApi {
    protected basePath = ApiConfig.apiPath;
    get defaultHeaders() : Headers { return ApiConfig.defaultHeaders };

    constructor(protected http: Http) {
    }

    /**
     * 指定したidのReservationを削除します
     * 
     * @param id ReservationのId
     */
    public reservationsIdDelete (id: string, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/reservation/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling reservationsIdDelete.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 指定したidの予約に関する詳細を返します
     * 
     * @param id ReservationのId
     */
    public reservationsIdGet (id: string, extraHttpRequestParams?: any ) : Observable<models.ReservationResponse> {
        const path = this.basePath + '/reservation/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling reservationsIdGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 指定したidのReservationに関する詳細を変更します
     * 
     * @param id ReservationのId
     * @param item 変更を行う詳細情報(idの値に格納された要素を変更)
     */
    public reservationsIdPut (id: string, item: models.ReservationRequest, extraHttpRequestParams?: any ) : Observable<models.ReservationResponse> {
        const path = this.basePath + '/reservation/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling reservationsIdPut.');
        }
        // verify required parameter 'item' is not null or undefined
        if (item === null || item === undefined) {
            throw new Error('Required parameter item was null or undefined when calling reservationsIdPut.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        headerParams.set('Content-Type', 'application/json');
        requestOptions.body = JSON.stringify(item);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Reservationの新規登録を行います
     * 
     * @param item 新規登録を行う際の詳細情報(ただしidの値は不要/サーバーが自動で採番)
     */
    public reservationsPost (item: models.ReservationRequest, extraHttpRequestParams?: any ) : Observable<models.ReservationResponse> {
        const path = this.basePath + '/reservation/';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'item' is not null or undefined
        if (item === null || item === undefined) {
            throw new Error('Required parameter item was null or undefined when calling reservationsPost.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        headerParams.set('Content-Type', 'application/json');
        requestOptions.body = JSON.stringify(item);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 利用中のReservationについて利用完了したことを通知します
     * 
     * @param reservationId ReservationのId
     */
    public returnReservationIdPost (reservationId: string, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/return/{reservation_id}'
            .replace('{' + 'reservation_id' + '}', String(reservationId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'reservationId' is not null or undefined
        if (reservationId === null || reservationId === undefined) {
            throw new Error('Required parameter reservationId was null or undefined when calling returnReservationIdPost.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return {};
                }
            });
    }

    /**
     * Reservationの検索を結果を返します
     * 
     * @param objectTagId 予約対象となるObjectTag
     * @param userName 予約ユーザーに含まれるuserのuser name
     * @param keywords Reservationの予約要件(部分一致)
     * @param sinceAt 指定時間以降に重なるものを検索 現在進行形の無期限貸出が存在する場合は、この値によらず含まれます。 
     * @param toAt 指定時間以前に重なるものを検索 現在進行形の無期限貸出が存在する場合は、この値によらず含まれます。 
     * @param includesPast 現在予約が終了しているものも検索に含めるかどうか。 defaultばfalseです。 
     */
    public searchReservationsGet (objectTagId?: string, userName?: string, keywords?: Array<string>, sinceAt?: Date, toAt?: Date, includesPast?: boolean, extraHttpRequestParams?: any ) : Observable<models.PaginationItem<models.JsonReservationResponse>> {
        const path = this.basePath + '/search/reservations';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (objectTagId !== undefined) {
            queryParameters.set('object_tag_id', String(objectTagId));
        }

        if (userName !== undefined) {
            queryParameters.set('user_name', String(userName));
        }

        if (keywords !== undefined) {
            queryParameters.set('keywords', String(keywords));
        }

        if (sinceAt !== undefined) {
            queryParameters.set('since_at', String(sinceAt));
        }

        if (toAt !== undefined) {
            queryParameters.set('to_at', String(toAt));
        }

        if (includesPast !== undefined) {
            queryParameters.set('includes_past', String(includesPast));
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
