/**
 * Tarusho.Server
 * Tarusho server API reference
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class ReservationApi {
    protected basePath = 'https://tarusho.vbcpp.net';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * 指定したidのReservationを削除します
     * 
     * @param id 削除を行うReservationのid
     */
    public reservationsDelete (id: boolean, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/reservations/';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling reservationsDelete.');
        }
        if (id !== undefined) {
            queryParameters.set('id', String(id));
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 指定したidの予約に関する詳細を返します
     * 
     * @param id ReservationのId
     */
    public reservationsGet (id: string, extraHttpRequestParams?: any ) : Observable<models.ReservationResponse> {
        const path = this.basePath + '/reservations/';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling reservationsGet.');
        }
        if (id !== undefined) {
            queryParameters.set('id', String(id));
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Reservationの新規登録を行います
     * 
     * @param item 新規登録を行う際の詳細情報(ただしidの値は不要/サーバーが自動で採番)
     */
    public reservationsPost (item: models.ReservationRequest, extraHttpRequestParams?: any ) : Observable<models.ReservationResponse> {
        const path = this.basePath + '/reservations/';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'item' is not null or undefined
        if (item === null || item === undefined) {
            throw new Error('Required parameter item was null or undefined when calling reservationsPost.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(item);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 指定したidのReservationに関する詳細を変更します
     * 
     * @param item 変更を行う詳細情報(idの値に格納された要素を変更)
     */
    public reservationsPut (item: models.ReservationRequest, extraHttpRequestParams?: any ) : Observable<models.ReservationResponse> {
        const path = this.basePath + '/reservations/';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'item' is not null or undefined
        if (item === null || item === undefined) {
            throw new Error('Required parameter item was null or undefined when calling reservationsPut.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(item);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Reservationの検索を結果を返します
     * 
     * @param objectTagId 予約対象となるObjectTag
     * @param userName 予約ユーザーに含まれるuserのuser name
     * @param keyword Reservationの予約要件(部分一致)
     * @param startAt 予約開始時刻
     * @param endAt 予約終了時刻。 現在進行形の無期限貸出が存在する場合は、この値によらず含まれます。 
     * @param includesPast 現在予約が終了しているものも検索に含めるかどうか。 defaultばfalseです。 
     */
    public searchReservationsGet (objectTagId?: string, userName?: string, keyword?: Array<string>, startAt?: Date, endAt?: Date, includesPast?: boolean, extraHttpRequestParams?: any ) : Observable<models.PaginationItem<models.ReservationResponse>> {
        const path = this.basePath + '/search/reservations';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (objectTagId !== undefined) {
            queryParameters.set('object_tag_id', String(objectTagId));
        }

        if (userName !== undefined) {
            queryParameters.set('user_name', String(userName));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startAt !== undefined) {
            queryParameters.set('start_at', String(startAt));
        }

        if (endAt !== undefined) {
            queryParameters.set('end_at', String(endAt));
        }

        if (includesPast !== undefined) {
            queryParameters.set('includes_past', String(includesPast));
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
