export { LicensePage } from '../pages/license/license';
export { HomePage } from '../pages/home/home';
export { LoginPage } from '../pages/login/login';
export { ObjectDetailsPage, MyUserItem } from '../pages/object/details/object-details';
export { ObjectListPage } from '../pages/object/list/object-list';
export { CategoryListPage } from '../pages/object/category-list/category-list';
export { ObjectRegistrationPage } from '../pages/object/registration/object-registration';
export { ObjectReservationPage } from '../pages/object/reservation/object-reservation';
export { UserDetailsPage } from '../pages/user/details/user-details';
export { UserListPage } from '../pages/user/list/user-list';